<a href="https://colab.research.google.com/github/MohamadMahdiDarvishi/Tensorflow/blob/main/Tensorflow_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Fundumantals of tensor flow
some of topics I am goning to cover in this nootebook :

* Creating `scalers` , `vectors` , `variables` and `contants`
* creating random tensors , shuffle order of tensor elements
*


## Prerequireties

In [ ]:
 # Imports
import tensorflow as tf
tf.__version__

'2.12.0'

##Creating `scalers` , `vectors` , `variables` and `contants`

as you may get it earlier these are more conceptual aspect of what we are going to cover :

* variables - representing different kind of data types (boolean,integer,..) in shape of vectors , tensors , ...
* constant - representing constant variables
* scalers - representing tensors or matrices with 0 dimension
* vectors - matrices with 1 dimension

In [ ]:
scaler = tf.Variable(5)
scaler

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=5>

In [ ]:
vector = tf.Variable([5 , 5])
vector

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 5], dtype=int32)>

In [ ]:
matrix = tf.Variable([[1 , 2 , 3],
                      [4 , 5 , 6]])
matrix

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
constant_matrix = tf.constant([[7 , 8 , 9],
                              [10 , 11 , 12]])
constant_matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

**Note :** we can't change matrix elements by assignment operators insted we use `assign()` method

In [ ]:
vector[0].assign(10)
vector

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  5], dtype=int32)>

**what is difference between constant and Variable ?** constants are unchangeable

looking at some features of tensors :

* Rank : `tensor.ndim`
* Shape : `tensor.shape`
* Size : `tensor.size`
* dimensions : `tensor[x,y]`

In [ ]:
constant_matrix.ndim

2

**Note :** we can not use `ndim` for **non** constant variables

In [ ]:
matrix.shape

TensorShape([2, 3])

In [ ]:
matrix[1][1] == matrix[1,1]

<tf.Tensor: shape=(), dtype=bool, numpy=True>

## Creating random tensors and Shuffle tensors

by setting seed to same numbers we would get same shuffles (order of elements) and random tensors

In [ ]:
# creating random tensors
random_1 = tf.random.Generator.from_seed(42).normal(shape = (2,2))
random_2 = tf.random.Generator.from_seed(42).normal(shape = (2,2))
random_2 == random_2

<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True]])>

**Note :** as you see by setting random seed we create the **reproducibility**

In [ ]:
# shuffle tensors (without setting seed)
not_shuffled = tf.constant([[1 , 2],
                            [3 , 4]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
# shuffled tensors (with setting seed)
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled , seed = 42)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [1, 2]], dtype=int32)>

## Other ways to make tensors

* ones
* zeros

In [ ]:
tf.ones([2 , 3  , 5])

<tf.Tensor: shape=(2, 3, 5), dtype=float32, numpy=
array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float32)>

In [ ]:
tf.zeros(shape = (3 , 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

## Turning numpy data unto tensors
main difference beteween numpy arrays and tensors is that tensors could run on GPUs or TPUs for faster procesing  

In [ ]:
import numpy as np
np_matrix = np.random.rand(3,2)
np_matrix

array([[0.03415142, 0.47904982],
       [0.27402042, 0.01874945],
       [0.16826989, 0.63833121]])

In [ ]:
tf_matrix = tf.constant(np_matrix)
tf_matrix

<tf.Tensor: shape=(3, 2), dtype=float64, numpy=
array([[0.03415142, 0.47904982],
       [0.27402042, 0.01874945],
       [0.16826989, 0.63833121]])>

In [ ]:
# or
tf_another_matrix = tf.constant(np_matrix , shape = (2,3))
tf_another_matrix

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[0.03415142, 0.47904982, 0.27402042],
       [0.01874945, 0.16826989, 0.63833121]])>

## Getting information from tensors

* Rank
* Shape
* Axis or dimension
* Size

In [ ]:
# Shape
tf_matrix.shape

TensorShape([3, 2])

In [ ]:
# Rank
tf_matrix.ndim

2

In [ ]:
# Size
tf.size(tf_matrix).numpy()

6

In [ ]:
# numpy method
tf_matrix.numpy()

array([[0.03415142, 0.47904982],
       [0.27402042, 0.01874945],
       [0.16826989, 0.63833121]])

In [ ]:
# tensor data type
tf_matrix.dtype

tf.float64

## Indexing tensors
tensorflow tensors can be indexed just like python lists

In [ ]:
rank_2_tensor = tf.constant([[1 , 2],
                             [3 , 4]])
rank_2_tensor[1,1]

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [ ]:
# or
rank_2_tensor[1][1].numpy()

4

**Note :** adding extra dimensions to our tensor

it would be really usefull when working with models inputs or outputs

In [ ]:
rank_3_tensor = tf.expand_dims(rank_2_tensor , axis = 0)
rank_3_tensor

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]]], dtype=int32)>

In [ ]:
# or
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

## Mainipulating tensors

arithmetic operations : `+`,`-`,`*`,`/`

arithmetic operations in tensorflow would hapen on every elemnents of tensors

In [ ]:
tf.random.set_seed(42)
sample_tensor = tf.random.uniform(shape = (2,2) , dtype = tf.int32 , maxval = 20 , seed = 42)
sample_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[13, 18],
       [10, 14]], dtype=int32)>

In [ ]:
sample_tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[130, 180],
       [100, 140]], dtype=int32)>

In [ ]:
sample_tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23, 28],
       [20, 24]], dtype=int32)>

**Matrix multiplication**

there are two important rules for matrix multiplication :

* the inner dimensions must be the same
* the resulting matrix would have outter dimensions


In [ ]:
tf.random.set_seed(42)
sample_tensor_2 = tf.random.uniform(shape = (2,3) , maxval = 20 , dtype = tf.int32 , seed = 42)
sample_tensor_2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[13, 18, 10],
       [14,  8,  1]], dtype=int32)>

In [ ]:
# as we could see inner dimensions have same value and resulting tensor would have shape : (2,3)
sample_tensor , sample_tensor_2

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[13, 18],
        [10, 14]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[13, 18, 10],
        [14,  8,  1]], dtype=int32)>)

In [ ]:
tf.matmul(sample_tensor , sample_tensor_2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[421, 378, 148],
       [326, 292, 114]], dtype=int32)>

In [ ]:
# or using python "@" operator
sample_tensor @ sample_tensor_2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[421, 378, 148],
       [326, 292, 114]], dtype=int32)>

In [ ]:
# creating a tensor that its dimensions doesn't match
tf.random.set_seed(42)
sample_tensor_3 = tf.random.uniform(shape = (3,2) , maxval = 20 ,seed = 42 , dtype = tf.int32)
sample_tensor_3

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[13, 18],
       [10, 14],
       [ 8,  1]], dtype=int32)>

In [ ]:
sample_tensor , sample_tensor_3

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[13, 18],
        [10, 14]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[13, 18],
        [10, 14],
        [ 8,  1]], dtype=int32)>)

In [ ]:
sample_tensor_reshape = tf.reshape(sample_tensor_3 , shape = (2,3))
sample_tensor_reshape

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[13, 18, 10],
       [14,  8,  1]], dtype=int32)>

In [ ]:
# resulting tensor shape would be : (2,3)
sample_tensor @ sample_tensor_reshape

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[421, 378, 148],
       [326, 292, 114]], dtype=int32)>

In [ ]:
# or we could use transpose
sample_tensor_transpose  = tf.transpose(sample_tensor_3)
sample_tensor_transpose

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[13, 10,  8],
       [18, 14,  1]], dtype=int32)>

In [ ]:
tf.matmul(sample_tensor , sample_tensor_transpose )

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[493, 382, 122],
       [382, 296,  94]], dtype=int32)>

**Note :**

tensor with same dimensions could be multiplied by `*` operator but resulting tensor is not produced by matrix multiplications and is just result of multiply of every element on same element on other matrix

**dot product**

Matrix multiplicaton is  also refered as dot product and we could `tf.tensordot` for doing that

In [ ]:
tf.tensordot(sample_tensor , sample_tensor_2 , axes = 1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[421, 378, 148],
       [326, 292, 114]], dtype=int32)>

## changing data type of tensors

* we can determine data type of tensors when we are creating tensors
* by the way we could change data type of created tensors by `tf.cast` function

In [ ]:
tensor_dtype = tf.constant([1.2 , 2.3] , dtype = tf.float32)
tensor_dtype.dtype

tf.float32

In [ ]:
tensor_dtype_2 = tf.cast(tensor_dtype , dtype = tf.float16)
tensor_dtype_2.dtype

tf.float16

## Aggregating tensors

**Aggregating tensors** means to put tensors with multiple values and get smaller  amount of values

some forms of tensors aggregation :

* get minimum value of tensor elements
* get maximum value of tensor elements
* get mean of tensor elements
* get sum of tensor elements

In [ ]:
aggregate_tensor = tf.constant(np.arange(20 , dtype = np.int32))
aggregate_tensor

<tf.Tensor: shape=(20,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19], dtype=int32)>

In [ ]:
tf.reduce_min(aggregate_tensor).numpy()

0

In [ ]:
tf.reduce_max(aggregate_tensor).numpy()

19

In [ ]:
tf.reduce_mean(aggregate_tensor).numpy()

9

In [ ]:
#  and if we want to get accurate answer we must change data type to float
tf.reduce_mean(tf.cast(aggregate_tensor , dtype = tf.float32)).numpy()

9.5

In [ ]:
tf.reduce_sum(aggregate_tensor).numpy()

190

**Note :** we could get absolute value of every elemnt of tensor by `tf.abs()`

In [ ]:
tf.abs(tf.constant([-20 , -30]))

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([20, 30], dtype=int32)>

we also could get following data of tensors :

* variation
* standar deviation

In [ ]:
# variation
import tensorflow_probability as tfp
tfp.stats.variance(aggregate_tensor).numpy()

33

**Note :** before getting standar deviation we must change data type to float

In [ ]:
# standat deviation
tf.math.reduce_std(tf.cast(aggregate_tensor, dtype = tf.float64)).numpy

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(), dtype=float64, numpy=5.766281297335398>>

In [ ]:
# vriance (another way)
tf.math.reduce_variance(tf.cast(aggregate_tensor , dtype = tf.float64)).numpy()

33.25

## Find positional maximum and minimum

In [ ]:
tf.random.set_seed(42)
pos_max_min_tensor = tf.random.uniform(shape = (1,50) , seed = 42)
pos_max_min_tensor

<tf.Tensor: shape=(1, 50), dtype=float32, numpy=
array([[0.4163028 , 0.26858163, 0.47968316, 0.36457133, 0.95471144,
        0.9418646 , 0.61483395, 0.35842144, 0.5936024 , 0.21551096,
        0.07745171, 0.57921314, 0.29180396, 0.26718032, 0.37012458,
        0.7161033 , 0.45877767, 0.11764562, 0.21073711, 0.5441973 ,
        0.9898069 , 0.38395858, 0.04683566, 0.8718462 , 0.25881708,
        0.873135  , 0.64698434, 0.41981232, 0.24148273, 0.09550059,
        0.9820819 , 0.1570208 , 0.2997682 , 0.36795306, 0.9453716 ,
        0.11056781, 0.52287626, 0.8305441 , 0.0020721 , 0.9594034 ,
        0.85630023, 0.3944497 , 0.22028875, 0.67066073, 0.01875746,
        0.48057055, 0.5953454 , 0.6847329 , 0.18988943, 0.12489867]],
      dtype=float32)>

In [ ]:
# maximum value position
tf.argmax(pos_max_min_tensor , axis = 1)

<tf.Tensor: shape=(1,), dtype=int64, numpy=array([20])>

In [ ]:
# minimum value position
tf.argmin(pos_max_min_tensor , axis = 1)

<tf.Tensor: shape=(1,), dtype=int64, numpy=array([38])>

In [ ]:
# we could use position value to find maximum value
pos_max_min_tensor[0 , tf.squeeze(tf.argmax(pos_max_min_tensor , axis = 1) , axis = 0)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9898069>

## Squeeze dimension (reducing dimensions)

In [ ]:
not_squeeze = tf.constant([[[ 22 , 23]]])
not_squeeze.shape

TensorShape([1, 1, 2])

In [ ]:
squeeze_tensor = tf.squeeze(not_squeeze , axis = 0)
squeeze_tensor.shape

TensorShape([1, 2])

##  some mathematical functions

* logaritm
* squaring
* squar root

**Note :** at first we use `tf.range` just like range function of python

In [ ]:
math_tensor = tf.range(10)
math_tensor

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
# Squaring
tf.square(math_tensor)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# finding square root
tf.sqrt(tf.cast(math_tensor , dtype = tf.float32))

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.       , 1.       , 1.4142135, 1.7320508, 2.       , 2.2360678,
       2.4494896, 2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
# logaritm
tf.math.log(tf.cast(math_tensor , dtype = tf.float32))

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([     -inf, 0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 ,
       1.7917595, 1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## \** one-hot encoding tensors \**

In [ ]:
some_list = [2,5,7]
tf.one_hot(some_list , depth = 10)

<tf.Tensor: shape=(3, 10), dtype=float32, numpy=
array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]], dtype=float32)>

In [ ]:
# another way
tf.one_hot(some_list , on_value = "yes" , off_value = "No" , depth = 9)

<tf.Tensor: shape=(3, 9), dtype=string, numpy=
array([[b'No', b'No', b'yes', b'No', b'No', b'No', b'No', b'No', b'No'],
       [b'No', b'No', b'No', b'No', b'No', b'yes', b'No', b'No', b'No'],
       [b'No', b'No', b'No', b'No', b'No', b'No', b'No', b'yes', b'No']],
      dtype=object)>

## finding access to GPU

**Note :**

bfore running below code cell we should firstly change runtime type from runtime menu to `T4 GPU`

In [ ]:
import tensorflow as tf
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Sun Aug 20 19:51:02 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P0    28W /  70W |    389MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------